- name: yum install nginx
  yum: name=nginx state=present
  notify: restart nginx

- name: create dir for custom config files
  file: dest=/etc/nginx/conf.d state=directory

- name: add basic config files
  template: src={{ item }} dest=/etc/nginx/{{ item }}
  with_items:
    - nginx.conf
    - conf.d/status.conf
    - conf.d/listen.conf
  notify: reload nginx

- name: chmod nginx log files
  file: path=/var/log/nginx/ mode=0755

- name: avoid too many open files error
  lineinfile:
    path: /etc/sysconfig/nginx
    line: 'NGINX_ULIMIT="-n 4096"'

- action: service name=nginx state=started enabled=yes
